- Quaver.API/Maps/Structures/HitObjectInfo.cs
Retrieves the correct timing point for objects. Partially the reason why arrow skin snaps weren't correct on multi-bpm maps.
> Fix GetTimingPoint returning wrong one

- Quaver.API/Enums/ModIdentifier.cs
- Quaver.API/Helpers/ModHelper.cs
- Quaver.API/Maps/Qua.cs
cc https://github.com/Quaver/Quaver/issues/406
I left the comma there so it's easier to add or reorder enum members without having to mess with commas.
Guess I'm conflicting with #20 so whoever gets in second has to change their bitshift :jerry:
> Add a NoLongNotes mod

- Quaver.Tools/Commands/ReplayBuildCommand.cs
- Quaver.Tools/Commands/ReplayCommand.cs
- Quaver.Tools/Commands/VirtualReplayPlayerCommand.cs
Never got build errors for these classes due to editing the Quaver.API submodule in the main Quaver solution instead of the Quaver.API solution.
> Replay variable changes in Quaver.Tools

- Quaver.API.Tests/Osu/Resources/Camellia - Backbeat Maniac (Evening) [Rewind VIP].qua
- Quaver.API/Enums/TimeSignature.cs
- Quaver.API/Maps/Parsers/OsuBeatmap.cs
- Quaver.API/Maps/Qua.cs
- Quaver.API/Maps/Structures/TimingPointInfo.cs
https://github.com/Quaver/Quaver/issues/534
Alright so I'm not fixing the test until we figure this out: since I added the time signature to the timing points, it's now emitted into YAML and is required to be present there, since it's either 4 or 3 and not 0. It's definitely desirable to omit the default value of 4 (and also the default value of 1 for hitsounds)—to reduce the number of useless lines and to preserve compatibility with old .qua files. What's the best way to do this? Convert the default of 4 to 0 before serialization and convert 0 to 4 right after parsing?
> Fix SV issues

- Quaver.API/Maps/Processors/Scoring/ScoreProcessor.cs
Fixes the hit difference graph (it's relying on `JudgementWindow` values and they were incorrect for replays with rates).
> ScoreProcessor: add missing InitializeMods()

- Quaver.API/Maps/Qua.cs
This affects maps where all timing points are after all hit objects.
> Return the first timing point BPM instead of crash

- Quaver.API/Maps/Parsers/OsuBeatmap.cs
Supersedes #85. Original PR got rid of the SpecialStyle property completely, which it shouldn't have
> Allow non-special style map conversions

- Quaver.API/Maps/Processors/Difficulty/Rulesets/Keys/DifficultyProcessorKeys.cs
when a map has patterns so slow that the calc determines them outside the boundaries for the lower threshold of a pattern (as defined in StrainConstantsKeys) it will isntead scale its qr value based on the nps of the difficulty (ranging from .4 to ~1.2) which adds a lot more scaling to beginner difficulties than there were before and will help guide beginners much better (no more easies being lower than beginners)
I also added another condition where if this specific part is in a much harder map it will impact it less.
> add scaling to beginner difficulties

- Quaver.API/Maps/Processors/Difficulty/Rulesets/Keys/DifficultyProcessorKeys.cs
Changes applied to my local ranked and unranked sets (all ranked maps are included): [Spreadsheet](https://docs.google.com/spreadsheets/d/1tLPmtzzDPP5hYrXe-Qo1ojKjxkqmg0gVJd8mV64tujo/edit#gid=2055591202)
Requires https://github.com/Quaver/Quaver/pull/2819 to be useable in client.
This prevents radical jumps in rating from crossing the threshold (Always Smiling used to jump from 37 to 31 at 1.2x to 1.25x)
Maps with breaks were heavily underrated at times because of the "average" approach taken with the strain values. This adjusts the impact of easy sections on the average of the map by computing a "continuity" value. This value is set from 1 (no breaks at all) to 0 (there is only a single short spike in the map with the rest being easy notes). The average continuity observed for the tested …
> Difficulty calculator improvements

- Quaver.API/Maps/Parsers/Stepmania/StepFile.cs
- Quaver.API/Maps/Qua.cs
Because we all love those random speedup because the charter made bpm change for sync purpose.
in more seriousness, .sm file are not really intented to have SV, it started supporting SV since .ssc file. Some .sm file do have some SV like effect with STOP for example, but no one do that for a long time, people just use .ssc.
Apparently it does exist really old chart that was make with Xmod in mind, but those are the old school charting style, nowadays people just use Cmod in all case anyways. And since chart that are supposed to be played on Cmod represent literally 99.9% of the chart in stepmania/etterna, i think it is safe to make them all play like Cmod by default.
This is specially useful considering Quaver want unranked leaderboard, and everyone just use the no SV modifier for obvious …
> Make stepfile have no SV by default

- Quaver.API.Tests/AutoMods/Resources/multi-mode-diff-name-1.qua
- Quaver.API.Tests/AutoMods/Resources/multi-mode-diff-name-2.qua
- Quaver.API/Maps/AutoMod/AutoModMapset.cs
- Quaver.API/Maps/AutoMod/Issues/Metadata/AutoModIssueMultiModeDiffName.cs
Allows for "Swan's 4K Beginner" instead of having to use "4K Swan's Beginner"
Related https://github.com/Quaver/Quaver.Wiki/pull/132
> Contain gamemode instead of prefix for multi-mode sets

- Quaver.API.Tests/Quaver.API.Tests.csproj
- Quaver.API.Tests/Quaver/Resources/regression-9-normalized.qua
- Quaver.API.Tests/Quaver/Resources/regression-9.qua
- Quaver.API.Tests/Quaver/TestCaseQua.cs
- Quaver.API/Maps/Qua.cs
This fixes a bug that I initially missed which results in different
behavior from old Quaver code and a mismatch between normalization and
denormalization when the following conditions are met:
1. BPMDoesNotAffectSV = false (old maps),
2. There's at least two timing points and at least one SV all on the
same StartTime.
In this case the SV was already considered when converting the first
timing point, even though it only applies to the last timing point.
We ran a check across ranked maps and found none that have this
configuration. I've manually tested a number of SV maps (both Quaver and
osu! converts) and found no change in behavior.
> Qua: Fix SV normalization with 2+ timing points and SV

- Quaver.API/Helpers/ModHelper.cs
Closes https://github.com/Quaver/Quaver/issues/1387
.05x rates sort with the normal rates
NSV no longer sorts before rate mods
Affects places where mods are listed in text format, such as the mods list at the top of song select.
> Make rate mods sort first in list

- Quaver.API/Maps/Qua.cs
Fixes errors when saving map after placing a note that prevents map to be edited after.
> Restore bookmark list when serialize finishes

- Quaver.API/Helpers/Objects.cs
[`BinaryFormatter` will become fully deprecated in .NET 9](https://github.com/dotnet/runtime/issues/98245), and already throws exceptions in .NET 8 since it's opt-in now. This pull request makes migrations to .NET 8 and up possible.
`XmlSerializer` in this case is an easy swap-in replacement. There may be some performance implications, but I haven't noticed any regressions when previewing or playing charts in the Quaver game, including extremely heavy/dense charts.
> Use XmlSerializer over BinaryFormatter

- Quaver.API/Maps/Parsers/OsuBeatmap.cs
Back then, osu! used to clamp SV values to 0.1, but that behavior changed sometime in 2019(?) to 0.01.
Modern SV charts rely on this a lot, such as [SPIRAL](https://osu.ppy.sh/beatmapsets/2115576#mania/4442623).
The example shown refers to `129975|2,130108|2,130241|2` (2:09.975).
> Set lower bound of osu! converted SVs to 0.01

- Quaver.API/Maps/Qua.cs
Fixes extremely niche edgecase with map backups that causes maps to not be backed up if the only difference between the new and old is a difference in the Legacy LN toggle. Any other difference still saves properly.
> Fix Qua equality

- Quaver.API/Replays/Replay.cs
[Opera Skaala - Heart of Light - 29686.zip](https://github.com/Quaver/Quaver.API/files/15242532/Opera.Skaala.-.Heart.of.Light.-.29686.zip)
In this map (SM convert), some notes overlap so it messes up the perfect replay. This map spams this error:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
at System.Collections.Generic.List`1.set_Item(Int32 index, T value)
at Quaver.Shared.Screens.Gameplay.Rulesets.Input.ReplayInputManagerKeys.HandleInput(Boolean forceInput) in D:\RiderProjects\QuaverCanary\Quaver.Shared\Screens\Gameplay\Rulesets\Input\ReplayInputManagerKeys.cs:line 142
```
Which is due to the use of arithmetic subtraction, instead of bit manipulation, of press state.
This PR resolves …
> Use bit manipulation instead of arithmetic subtraction for generating perfect replay releases

- Quaver.API/Maps/Processors/Difficulty/Rulesets/Keys/DifficultyProcessorKeys.cs
Fixes error throwing when there are >= 2 scratch lane notes and nothing else.
> Return difficulty 0 when StrainSolverData is empty

- Quaver.API/Maps/Parsers/Stepmania/StepFile.cs
[Flashes (25).zip](https://github.com/user-attachments/files/17090035/Flashes.25.zip)
Check the last measure. The snap isnt right without the change.
> [StepMania] Don't count the semicolon as a row to solve the wrong rhythm in the last measure

- Quaver.API.Tests/Quaver/TestCaseQua.cs
- Quaver.API/Maps/Qua.cs
- Quaver.API/Maps/Structures/ScrollGroup.cs
- Quaver.API/Maps/Structures/TimingGroup.cs
Seems like implementing an equality comparer is not viable because we have class inheritance. So, I override `Equals()` instead.
> Compare Qua.TimingGroups properly

- Quaver.API/Maps/Qua.cs
Instead of "" and "*", this should be more intuitive.
> Make default name for Default and Global Scroll group $Default and $Global

- Quaver.API.Tests/Quaver/TestCaseQua.cs
- Quaver.API/Maps/Qua.cs
- Quaver.API/Maps/Structures/ScrollGroup.cs
Since SV list is now a reference inside another reference (DefaultTimingGroup) in Qua, shallow MemberwiseClone() no longer applies. So we need to use DeepClone instead.
> Deep clone map when (de)normalizing SVs
