Quaver/Quaver.API

Quaver.API/Replays/Replay.cs
Quaver.API/Replays/ReplayAutoplayFrame.cs

Found a few mistakes in comment lines when I was browsing through classes. Decided to fix them right away.

Fixed mistakes in comments

---

Quaver.API/Replays/Virtual/VirtualReplayPlayer.cs

This has come up when I tried using it for the hit difference graph purposes.

Virtual replay player fixes

---

Quaver.API/Helpers/MathHelper.cs
Quaver.API/Maps/Parsers/OsuBeatmap.cs
Quaver.Tools/Commands/ConvertOsuCommand.cs
Quaver.Tools/Program.cs

Fixes [Quaver/Quaver#438](https://github.com/Quaver/Quaver/issues/438)
Fixes [Quaver/Quaver#347](https://github.com/Quaver/Quaver/issues/347)
Fixes [Quaver/Quaver#263](https://github.com/Quaver/Quaver/issues/263)

Fix osu conversions

---

Quaver.API/Maps/Qua.cs

Add Qua.ApplyMods()

---

Quaver.API/Replays/Replay.cs

Cross commit with Quaver/Quaver#435
Merge this before #20

Added replay versioning

---

Quaver.API/Enums/ModIdentifier.cs
Quaver.API/Helpers/ModHelper.cs
Quaver.API/Maps/Qua.cs
Quaver.API/Quaver.API.csproj
Quaver.API/Replays/Replay.cs

Added Randomize Mod Identifier

---

Quaver.API/Replays/Virtual/VirtualReplayPlayer.cs

See https://github.com/Quaver/Quaver/pull/526

Use hit object start and end time for misses

---

Quaver.API/Enums/ModIdentifier.cs
Quaver.API/Helpers/ModHelper.cs

Add 0.?5x rates

---

Quaver.API/Maps/Parsers/OsuBeatmap.cs
Quaver.API/Maps/Qua.cs

https://github.com/Quaver/Quaver/issues/608

Add degenerate LN check

---

Quaver.API.Tests/Quaver.API.Tests.csproj
Quaver.API.Tests/Quaver/Resources/issue-quaver-721.qua
Quaver.API.Tests/Quaver/TestCaseQua.cs
Quaver.API/Maps/Qua.cs

Fixes https://github.com/Quaver/Quaver/issues/721

Full LN: preserve single objects in lanes

---

Quaver.API/Enums/ModIdentifier.cs
Quaver.API/Enums/MultiplayerHealthType.cs
Quaver.API/Maps/Processors/Scoring/Multiplayer/ScoreProcessorMultiplayer.cs
Quaver.API/Maps/Processors/Scoring/ScoreProcessor.cs
Quaver.API/Maps/Processors/Scoring/ScoreProcessorKeys.cs

Adds a class to `ScoreProcessor` for handling scoring in multiplayer environments. Includes two different ways of handling health/lives.

Multiplayer Score Processor

---

Quaver.API/Maps/Processors/Scoring/Data/HitStatistics.cs
Quaver.API/Maps/Processors/Scoring/ScoreProcessor.cs

Moving this one over from https://github.com/Quaver/Quaver/pull/952.

Add HitStatistics and a ScoreProcessor method to compute them

---

Quaver.API/Helpers/ModHelper.cs

Rename IV to INV

---

Quaver.API/Replays/Replay.cs

Before Mirror would result in all bits from the 32-nd to the 64-th set
in Mods, which would subsequently break other parts of the code.

Replay: fix reading replays with Mirror

---

Quaver.API/Maps/Parsers/Stepmania/StepFile.cs
Quaver.API/Maps/Parsers/Stepmania/StepFileBPM.cs
Quaver.API/Maps/Parsers/Stepmania/StepFileStop.cs

Addresses the issue: https://github.com/Quaver/Quaver/issues/1463

Fix multi-line bpms and stops not being parsed

---

Quaver.API/Maps/Structures/EditorLayerInfo.cs

Needed to let plugins manipulate editor layers.

Register EditorLayerInfo with MoonSharp

---

Quaver.API/Maps/Qua.cs

Return null for times before first SV for Qua.GetScrollVelocityAt()

---

Quaver.API/Maps/Qua.cs

Forgot to have the game actually save this in qua files smh

Reflect timing point hidden value when serializing Qua

---

Quaver.Tools/Commands/VirtualReplayPlayerCommand.cs

Make them correspond to actual releases, not all LN hits.
@AiAe does this work?

VirtualReplay tool: Fix LN release hit marks

---

Quaver.API/Maps/Parsers/OsuBeatmap.cs

Map.LoadQua() from Quaver.Shared which calls this needs to support this argument.

OsuBeatmap: Add checkValidity argument to ToQua()

---

Quaver.API/Enums/ModIdentifier.cs
Quaver.API/Helpers/ModHelper.cs
Quaver.API/Maps/Processors/Scoring/ScoreProcessor.cs
Quaver.API/Maps/Processors/Scoring/ScoreProcessorKeys.cs

https://github.com/Quaver/Quaver/pull/3516

Implement No Miss Modifier

---

Quaver.API/Maps/AutoMod/AutoMod.cs

Fixes https://github.com/Quaver/Quaver/issues/3659

Fix incorrect standardization detection

---

Quaver.API/Maps/AutoMod/AutoMod.cs

Fix incorrect minimum banner dimensions

---

Quaver.API.Tests/Quaver/TestCaseQua.cs
Quaver.API/Maps/Qua.cs

They are not supposed to affect the scratch lane. Resolves #97.

Fix 7K+1 mirror, randomize and LN mods

---

Quaver.API/Maps/Qua.cs

Used in https://github.com/Quaver/Quaver/pull/4078, see there for more details.

Add "LegacyLNRendering" property on the .qua file format

---

Quaver.API.Tests/Quaver/Resources/cheat-normalized.qua
Quaver.API/Maps/Qua.cs

Fixes [this issue](https://github.com/Quaver/Quaver/issues/4081)

Fix osu! infinite BPMs

---

Quaver.API/Maps/Qua.cs

Fix SSF being serialized for every timing group except the default.

Fix SSF not serialized for default group

---

Quaver.API/Maps/Qua.cs

Resolves https://github.com/Quaver/Quaver/issues/4389
I am mindblocking code now

Fix global timing group not being loaded properly
